---
- name: Add configuration script
  file:
    src: ~/.config.d/roles/utils/files/configure
    dest: /usr/local/bin/configure
    state: link
  tags: utils

- name: Add reconfiguration script
  file:
    src: ~/.config.d/roles/utils/files/reconfigure
    dest: /usr/local/bin/reconfigure
    state: link
  tags: utils
